### ISSUE TITLE
While running this command "add -date 2024-05-10 temp Misc" application crashes

### ISSUE THREAD

**Issue by abhijeetjain04** [Aditya5991/ExpenseManager#8]

**Comment by Aditya5991** [comment]
Fixed in : https://github.com/Aditya5991/ExpenseManager/commit/82943ba0776437e495f190f6ca1445f346e717d0

**Comment by Aditya5991** [comment]
https://github.com/Aditya5991/ExpenseManager/commit/c8a9e8ecce4ee06484673f94d325fc15dc6757c9
